### ISSUE TITLE
Art style ideas

### ISSUE THREAD

**Issue by ChielBruin** [Taeir/ContextProject-MIGI2#12]
Post your ideas for the art style here.

**Comment by ChielBruin** [comment]
https://www.google.nl/search?q=the+witness&safe=off&espv=2&biw=1366&bih=658&source=lnms&tbm=isch&sa=X&ved=0ahUKEwil9re956vMAhVBI8AKHTV8BI4Q_AUIBygC

**Comment by Geweldig** [comment]
Art style ideas have been decided.
