### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by Taeir2** [Taeir/ContextProject-MIGI2#284]
As a player, I want the web interface to be responsive, so that my actions happen immediately.

As a player, I want the web interface to update quickly, so that I can see what's happening in the game.

This task has the following subtasks:
- #285 Websockets - Explore possibilities
- #286 Websockets - Implement websockets - Clientside
- #287 Websockets - Implement websockets - Serverside
- #288 Websockets - Test client server interaction

**Comment by Taeir** [comment]
This task is superseded by #352 in sprint 7.
